name: Auto Video Upload

on:
schedule:
- cron: "30 15 * * *"  # 9:00 PM IST
workflow_dispatch:       # allows manual trigger too

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout repo
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: |
      pip install -r requirements.txt

  - name: Run generator
    env:
      YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
      YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    run: python generate_and_upload.py
